package sop_corba;


/**
* sop_corba/ControladorNotificacionesInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./interface.idl
* martes 9 de agosto de 2022 06:37:45 PM CDT
*/

public interface ControladorNotificacionesInt extends ControladorNotificacionesIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ControladorNotificacionesInt
