package sop_corba;


/**
* sop_corba/_ControladorNotificacionesIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./interface.idl
* martes 9 de agosto de 2022 06:37:45 PM CDT
*/

public class _ControladorNotificacionesIntStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.ControladorNotificacionesInt
{

  public sop_corba.ControladorNotificacionesIntPackage.NotificacionDTO[] listarNotificaciones ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarNotificaciones", true);
                $in = _invoke ($out);
                sop_corba.ControladorNotificacionesIntPackage.NotificacionDTO $result[] = sop_corba.ControladorNotificacionesIntPackage.ListaNotificacionesHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarNotificaciones (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarNotificaciones

  public boolean registrarNotificacion (sop_corba.ControladorNotificacionesIntPackage.NotificacionDTO objNotificacion)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarNotificacion", true);
                sop_corba.ControladorNotificacionesIntPackage.NotificacionDTOHelper.write ($out, objNotificacion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarNotificacion (objNotificacion        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarNotificacion

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ControladorNotificacionesInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ControladorNotificacionesIntStub
