package sop_corba;


/**
* sop_corba/ControladorNotificacionesIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./interface.idl
* martes 9 de agosto de 2022 06:37:45 PM CDT
*/

public abstract class ControladorNotificacionesIntPOA extends org.omg.PortableServer.Servant
 implements sop_corba.ControladorNotificacionesIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("listarNotificaciones", new java.lang.Integer (0));
    _methods.put ("registrarNotificacion", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/ControladorNotificacionesInt/listarNotificaciones
       {
         sop_corba.ControladorNotificacionesIntPackage.NotificacionDTO $result[] = null;
         $result = this.listarNotificaciones ();
         out = $rh.createReply();
         sop_corba.ControladorNotificacionesIntPackage.ListaNotificacionesHelper.write (out, $result);
         break;
       }

       case 1:  // sop_corba/ControladorNotificacionesInt/registrarNotificacion
       {
         sop_corba.ControladorNotificacionesIntPackage.NotificacionDTO objNotificacion = sop_corba.ControladorNotificacionesIntPackage.NotificacionDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarNotificacion (objNotificacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/ControladorNotificacionesInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ControladorNotificacionesInt _this() 
  {
    return ControladorNotificacionesIntHelper.narrow(
    super._this_object());
  }

  public ControladorNotificacionesInt _this(org.omg.CORBA.ORB orb) 
  {
    return ControladorNotificacionesIntHelper.narrow(
    super._this_object(orb));
  }


} // class ControladorNotificacionesIntPOA
