package sop_corba.ControladorNotificacionesIntPackage;


/**
* sop_corba/ControladorNotificacionesIntPackage/NotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./interface.idl
* martes 9 de agosto de 2022 06:37:45 PM CDT
*/

public final class NotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String tipo = null;
  public float valor = (float)0;
  public String lugar = null;
  public String fecha = null;
  public String medio = null;
  public int nit = (int)0;

  public NotificacionDTO ()
  {
  } // ctor

  public NotificacionDTO (int _id, String _tipo, float _valor, String _lugar, String _fecha, String _medio, int _nit)
  {
    id = _id;
    tipo = _tipo;
    valor = _valor;
    lugar = _lugar;
    fecha = _fecha;
    medio = _medio;
    nit = _nit;
  } // ctor

} // class NotificacionDTO
